#include "ShaderWater.h"

bool ShaderWater::CreateShader()
{
    std::string vert =
        "#version 460 core\n"
        "layout(location = 0) in vec3 aPos;\n"
        "out vec4 ScreenPos;\n"
        "out vec3 WorldPos;\n"
        "uniform mat4 model;\n"
        "uniform mat4 view;\n"
        "uniform mat4 projection;\n"
        "void main() {\n"
        "    vec4 wPos = model * vec4(aPos, 1.0);\n"
        "    WorldPos = wPos.xyz;\n"
        "    vec4 clipPos = projection * view * wPos;\n"
        "    ScreenPos = clipPos;\n"
        "    gl_Position = clipPos;\n"
        "}\n";

    std::string frag =
        "#version 460 core\n"
        "out vec4 FragColor;\n"
        "in vec4 ScreenPos;\n"
        "in vec3 WorldPos;\n"
        "uniform sampler2D uSceneDepthMap;\n"
        "uniform mat4 uInverseVP;\n"
        "uniform float uTime;\n"
        "uniform vec3 uWaterColor;\n"
        "uniform vec3 uFoamColor;\n"
        "uniform float uFoamThickness;\n"
        "uniform float uFoamOffset;\n"
        "\n"
        "vec3 GetWorldPosFromDepth(vec2 ndc, float rawDepth) {\n"
        "    vec4 clipSpace = vec4(ndc * 2.0 - 1.0, rawDepth * 2.0 - 1.0, 1.0);\n"
        "    vec4 worldSpace = uInverseVP * clipSpace;\n"
        "    return worldSpace.xyz / worldSpace.w;\n"
        "}\n"
        "\n"
        "float hash(vec2 p) {\n"
        "    return fract(sin(dot(p, vec2(12.9898, 78.233))) * 43758.5453);\n"
        "}\n"
        "\n"
        "float noise(vec2 p) {\n"
        "    vec2 i = floor(p);\n"
        "    vec2 f = fract(p);\n"
        "    vec2 u = f * f * (3.0 - 2.0 * f);\n"
        "    return mix(mix(hash(i + vec2(0.0, 0.0)), hash(i + vec2(1.0, 0.0)), u.x),\n"
        "               mix(hash(i + vec2(0.0, 1.0)), hash(i + vec2(1.0, 1.0)), u.x), u.y);\n"
        "}\n"
        "\n"
        "float fbm(vec2 p) {\n"
        "    float f = 0.0;\n"
        "    f += 0.5000 * noise(p); p = p * 2.02;\n"
        "    f += 0.2500 * noise(p); p = p * 2.03;\n"
        "    f += 0.1250 * noise(p);\n"
        "    return f;\n"
        "}\n"
        "\n"
        "void main() {\n"
        "    vec2 ndc = (ScreenPos.xy / ScreenPos.w) * 0.5 + 0.5;\n"
        "    float rawDepth = texture(uSceneDepthMap, ndc).r;\n"
        "\n"
        "    vec3 terrainWorldPos = GetWorldPosFromDepth(ndc, rawDepth);\n"
        "    float verticalDepth = WorldPos.y - terrainWorldPos.y;\n"
        "\n"
        "    float tideShore = sin(uTime * 1.0) * 0.05;\n"
        "    float wobbleShore = (sin(WorldPos.x * 3.0 + uTime * 1.2) + cos(WorldPos.z * 3.0 - uTime * 0.9)) * 0.01;\n"
        "    float depthShore = verticalDepth + wobbleShore - tideShore;\n"
        "\n"
        "    float tideLine = sin(uTime * 1.4 + 1.5) * 0.1;\n"
        "    float wobbleLine = (sin(WorldPos.x * 4.0 - uTime * 1.5) + cos(WorldPos.z * 4.0 + uTime * 1.2)) * 0.01;\n"
        "    float depthLine = verticalDepth + wobbleLine - tideLine;\n"
        "\n"
        "    float tideDark = sin(uTime * 0.7 + 3.0) * 0.15;\n"
        "    float wobbleDark = (sin(WorldPos.x * 2.0 + uTime * 0.5) + cos(WorldPos.z * 2.0 - uTime * 0.5)) * 0.01;\n"
        "    float depthDark = verticalDepth + wobbleDark - tideDark;\n"
        "\n"
        "    float shoreEnd = 0.25; \n"
        "    float lineStart = 0.45;\n"
        "    float lineEnd = 0.50;\n"
        "    float darkStart = 0.70;\n"
        "    float darkEnd = 1.30;\n"
        "\n"
        "    float isShore = 1.0 - step(shoreEnd, depthShore); \n"
        "    float isLine = step(lineStart, depthLine) - step(lineEnd, depthLine);\n"
        "    float isDark = step(darkStart, depthDark) - step(darkEnd, depthDark);\n"
        "\n"
        "    vec2 uv = WorldPos.xz * 0.08; \n"
        "    \n"
        "    float n1 = fbm(uv + vec2( uTime * 0.06,  uTime * 0.05));\n"
        "    float n2 = fbm(uv + vec2(-uTime * 0.04, -uTime * 0.07));\n"
        "    float n = (n1 + n2) * 0.5;\n"
        "    \n"
        "    float lineas = abs(fract(n * 3.5) - 0.5);\n"
        "    float lineWeight = smoothstep(0.05, 0.01, lineas);\n"
        "    \n"
        "    float mask = smoothstep(0.3, 0.7, noise(WorldPos.xz * 0.15 + sin(uTime * 0.2)));\n"
        "    float waterLines = lineWeight * mask;\n"
        "\n"
        "    vec3 colorMar = vec3(0.427, 0.541, 0.549);      \n"
        "    vec3 colorLineasRandom = vec3(0.487, 0.621, 0.639); \n"
        "    vec3 colorLineaLejos = vec3(0.299, 0.379, 0.384); \n"
        "    vec3 colorLineaFina = vec3(0.302, 0.714, 0.675);  \n"
        "    vec3 colorOrilla = vec3(0.964, 0.937, 0.878);   \n"
        "\n"
        "    vec3 finalColor = colorMar;\n"
        "    \n"
        "    finalColor = mix(finalColor, colorLineasRandom, waterLines);\n"
        "\n"
        "    finalColor = mix(finalColor, colorLineaLejos, isDark);\n"
        "    finalColor = mix(finalColor, colorLineaFina, isLine);\n"
        "    finalColor = mix(finalColor, colorOrilla, isShore);\n"
        "\n"
        "    FragColor = vec4(finalColor, 1.0);\n"
        "}\n";

    return LoadFromSource(vert.c_str(), frag.c_str());
}