#include "ShaderStandard.h"

bool ShaderStandard::CreateShader()
{
    std::string vert = std::string(shaderHeader) + skinningDeclarations + skinningFunction +
        "layout(location = 0) in vec3 aPos;\n"
        "layout(location = 1) in vec3 aNormal;\n"
        "layout(location = 2) in vec2 aTexCoord;\n"
        "layout(location = 3) in ivec4 boneIDs;\n"
        "layout(location = 4) in vec4 weights;\n"
        "layout(location = 5) in vec3 aTangent;\n"
        "\n"
        "out VS_OUT {\n"
        "    vec3 FragPos;\n"
        "    vec2 TexCoord;\n"
        "    vec3 Normal;\n"
        "    vec4 FragPosLightSpace;\n"
        "} vs_out;\n"
        "\n"
        "uniform mat4 lightSpaceMatrix;\n"
        "\n"
        "void main() {\n"
        "    mat4 skinMat = GetSkinMatrix(boneIDs, weights);\n"
        "    vec4 worldPos = model * skinMat * vec4(aPos, 1.0);\n"
        "    \n"
        "    vs_out.FragPos = worldPos.xyz;\n"
        "    vs_out.TexCoord = aTexCoord;\n"
        "    vs_out.FragPosLightSpace = lightSpaceMatrix * worldPos;\n"
        "    \n"
        "    mat3 normalMatrix = transpose(inverse(mat3(model * skinMat)));\n"
        "    vs_out.Normal = normalize(normalMatrix * aNormal);\n"
        "    \n"
        "    gl_Position = projection * view * worldPos;\n"
        "}\n";

    std::string frag =
        "#version 460 core\n"
        "out vec4 FragColor;\n"
        "\n"
        "in VS_OUT {\n"
        "    vec3 FragPos;\n"
        "    vec2 TexCoord;\n"
        "    vec3 Normal;\n"
        "    vec4 FragPosLightSpace;\n"
        "} fs_in;\n"
        "\n"
        "uniform sampler2D uAlbedoMap;\n"
        "uniform sampler2D uNormalMap;\n"
        "uniform sampler2D uMetallicMap;\n"
        "uniform sampler2D uOcclusionMap;\n"
        "uniform sampler2D uHeightMap;\n"
        "uniform sampler2D uShadowMap;\n"
        "\n"
        "uniform vec4  uColor;\n"
        "uniform float uHeightScale;\n"
        "uniform float uMetallic;\n"
        "uniform float uRoughness;\n"
        "uniform vec2  uTiling;\n"
        "uniform vec2  uOffset;\n"
        "uniform vec3  viewPos;\n"
        "\n"
        "uniform bool uUseNormalMap;\n"
        "uniform bool uUseMetallicMap;\n"
        "uniform bool uUseOcclusionMap;\n"
        "uniform bool uUseHeightMap;\n"
        "uniform bool uShadowsEnabled;\n" 
        "\n"
        "struct DirLightGLSL {\n"
        "    vec3 direction; float _p0;\n"
        "    vec3 ambient;   float _p1;\n"
        "    vec3 diffuse;   float _p2;\n"
        "    vec3 specular;  float _p3;\n"
        "};\n"
        "\n"
        "struct PointLightGLSL {\n"
        "    vec3 position;  float _p0;\n"
        "    vec3 ambient;   float _p1;\n"
        "    vec3 diffuse;   float _p2;\n"
        "    vec3 specular;  float _p3;\n"
        "    float constant;\n"
        "    float linear;\n"
        "    float quadratic;\n"
        "    float _p4;\n"
        "};\n"
        "\n"
        "struct SpotLightGLSL {\n"
        "    vec3 position;    float _p0;\n"
        "    vec3 direction;   float _p1;\n"
        "    vec3 ambient;     float _p2;\n"
        "    vec3 diffuse;     float _p3;\n"
        "    vec3 specular;    float _p4;\n"
        "    float cutOff;\n"
        "    float outerCutOff;\n"
        "    float constant;\n"
        "    float linear;\n"
        "    float quadratic;\n"
        "    float _p5; float _p6; float _p7;\n"
        "};\n"
        "\n"
        "layout(std430, binding = 2) readonly buffer DirLightBuffer   { DirLightGLSL   dirLights[];   };\n"
        "layout(std430, binding = 3) readonly buffer PointLightBuffer { PointLightGLSL pointLights[]; };\n"
        "layout(std430, binding = 4) readonly buffer SpotLightBuffer  { SpotLightGLSL  spotLights[];  };\n"
        "\n"
        "uniform int numDirLights;\n"
        "uniform int numPointLights;\n"
        "uniform int numSpotLights;\n"
        "\n"
        "float ShadowCalculation(vec4 fragPosLightSpace, vec3 geoNormal, vec3 lightDir) {\n"
        "    if (!uShadowsEnabled) return 0.0;\n" 
        "\n"
        "    vec3 projCoords = fragPosLightSpace.xyz / fragPosLightSpace.w;\n"
        "    projCoords = projCoords * 0.5 + 0.5;\n"
        "    if (projCoords.z > 1.0) return 0.0;\n"
        "\n"
        "    // el bias sirve para que no haya shadow acne, ahora esta en dinamico para pruebas 0\n"
        "    float bias = max(0.005 * (1.0 - dot(geoNormal, lightDir)), 0.0005);\n"
        "\n"
        "    float shadow = 0.0;\n"
        "    vec2 texelSize = 1.0 / textureSize(uShadowMap, 0);\n"
        "    for (int x = -1; x <= 1; ++x) {\n"
        "        for (int y = -1; y <= 1; ++y) {\n"
        "            float pcfDepth = texture(uShadowMap, projCoords.xy + vec2(x, y) * texelSize).r;\n"
        "            shadow += (projCoords.z - bias) > pcfDepth ? 1.0 : 0.0;\n"
        "        }\n"
        "    }\n"
        "    return shadow / 9.0;\n"
        "}\n"
        "\n"

        "vec2 ParallaxMapping(vec2 texCoords, vec3 viewDir) {\n"
        "    const float minLayers = 8.0;\n"
        "    const float maxLayers = 32.0;\n"
        "    float numLayers = mix(maxLayers, minLayers, abs(viewDir.z));\n"
        "    float layerDepth = 1.0 / numLayers;\n"
        "    float currentDepth = 0.0;\n"
        "    vec2 deltaUV = viewDir.xy * uHeightScale / (abs(viewDir.z) + 0.42) / numLayers;\n"
        "    vec2 currentUV = texCoords;\n"
        "    float currentHeight = texture(uHeightMap, currentUV).r;\n"
        "    for(int i = 0; i < 32 && currentDepth < currentHeight; ++i) {\n"
        "        currentUV -= deltaUV;\n"
        "        currentHeight = texture(uHeightMap, currentUV).r;\n"
        "        currentDepth += layerDepth;\n"
        "    }\n"
        "    vec2 prevUV = currentUV + deltaUV;\n"
        "    float afterDepth  = currentHeight - currentDepth;\n"
        "    float beforeDepth = texture(uHeightMap, prevUV).r - currentDepth + layerDepth;\n"
        "    float weight = afterDepth / (afterDepth - beforeDepth);\n"
        "    vec2 finalUV = mix(currentUV, prevUV, weight);\n"
        "    // Atenuar el efecto segun angulo para suavizar bordes\n"
        "    float edgeFade = smoothstep(0.0, 0.3, abs(viewDir.z));\n"
        "    return mix(texCoords, finalUV, edgeFade);\n"
        "}\n"
        "\n"
        "vec3 CalcLightContrib(vec3 lightDir, vec3 diffuseColor, vec3 specularColor,\n"
        "                      vec3 norm, vec3 viewDir,\n"
        "                      vec3 albedo, float metallic, float roughness) {\n"
        "    vec3 L = normalize(lightDir);\n"
        "    float diff = max(dot(norm, L), 0.0);\n"
        "    vec3 H = normalize(L + viewDir);\n"
        "    float shininess = (1.0 - clamp(roughness, 0.05, 1.0)) * 128.0 + 1.0;\n"
        "    float spec = pow(max(dot(norm, H), 0.0), shininess);\n"
        "    vec3 F0 = mix(vec3(0.04), albedo, metallic);\n"
        "    vec3 diffContrib = diffuseColor  * diff * albedo * (1.0 - metallic);\n"
        "    vec3 specContrib = specularColor * spec * F0;\n"
        "    return diffContrib + specContrib;\n"
        "}\n"
        "\n"
        "void main() {\n"
        "    vec2 uv = fs_in.TexCoord * uTiling + uOffset;\n"
        "    vec3 viewDir = normalize(viewPos - fs_in.FragPos);\n"
        "    vec3 geoNormal = normalize(fs_in.Normal);\n"
        "\n"
        "    // TBN (tangent, bitangent and normal) manual to avoid the problem of empty tangents (meaning that if there is no normal map, there is no shadow)\n"
        "    // 1. Parallax Mapping (solo si hay height map activo)\n"
        "    //if(uUseHeightMap && uHeightScale > 0.0) {\n"
        "    //    vec3 viewDirTangent = normalize(vec3(\n"
        "    //        dot(viewDir, fs_in.TBN[0]),\n"
        "    //        dot(viewDir, fs_in.TBN[1]),\n"
        "    //        dot(viewDir, fs_in.TBN[2])\n"
        "    //    ));\n"
        "    //    uv = ParallaxMapping(uv, viewDirTangent);\n"
        "    //}\n"
        "\n"
        "    // 2. Normal Mapping (only if a normal map is active)\n"
        "    vec3 normal;\n"
        "    if(uUseNormalMap) {\n"
        "        vec3 bitangent = cross(geoNormal, vec3(1.0, 0.0, 0.0));\n"
        "        if (length(bitangent) < 0.001) bitangent = cross(geoNormal, vec3(0.0, 0.0, 1.0));\n"
        "        bitangent = normalize(bitangent);\n"
        "        vec3 tangent = normalize(cross(bitangent, geoNormal));\n"
        "        mat3 TBN = mat3(tangent, bitangent, geoNormal);\n"
        "\n"
        "        normal = texture(uNormalMap, uv).rgb * 2.0 - 1.0;\n"
        "        normal = normalize(TBN * normal);\n"
        "    } else {\n"
        "        normal = geoNormal;\n"
        "    }\n"
        "\n"
        "    vec4 texColor = texture(uAlbedoMap, uv);\n"
        "    vec3 albedo = pow(texColor.rgb, vec3(2.2)) * uColor.rgb;\n"
        "    float metallic = uUseMetallicMap ? texture(uMetallicMap, uv).r * uMetallic : uMetallic;\n"
        "    float ao = uUseOcclusionMap ? texture(uOcclusionMap, uv).r : 1.0;\n"
        "    float roughness = clamp(uRoughness, 0.05, 1.0);\n"
        "\n"
        "    vec3 result = vec3(0.0);\n"
        "\n"
        "    for (int i = 0; i < numDirLights; ++i) {\n"
        "        vec3 lightDir = normalize(-dirLights[i].direction);\n"
        "        \n"
        "        float shadow = (i == 0) ? ShadowCalculation(fs_in.FragPosLightSpace, geoNormal, lightDir) : 0.0;\n"
        "\n"
        "        vec3 ambient = dirLights[i].ambient * albedo * ao;\n"
        "        vec3 contrib = CalcLightContrib(lightDir, dirLights[i].diffuse, dirLights[i].specular, \n"
        "                                        normal, viewDir, albedo, metallic, roughness);\n"
        "        result += ambient + contrib * (1.0 - shadow) * ao;\n"
        "    }\n"
        "\n"
        "    for (int i = 0; i < numPointLights; ++i) {\n"
        "        float dist = length(pointLights[i].position - fs_in.FragPos);\n"
        "        float attenuation = 1.0 / (pointLights[i].constant + pointLights[i].linear * dist + pointLights[i].quadratic * dist * dist);\n"
        "        vec3 contrib = CalcLightContrib(pointLights[i].position - fs_in.FragPos, pointLights[i].diffuse, pointLights[i].specular,\n"
        "                                        normal, viewDir, albedo, metallic, roughness);\n"
        "        result += (pointLights[i].ambient * albedo + contrib) * attenuation * ao;\n"
        "    }\n"
        "\n"
        "    for (int i = 0; i < numSpotLights; ++i) {\n"
        "        vec3 L = normalize(spotLights[i].position - fs_in.FragPos);\n"
        "        float theta = dot(L, normalize(-spotLights[i].direction));\n"
        "        float epsilon = spotLights[i].cutOff - spotLights[i].outerCutOff;\n"
        "        float intensity = clamp((theta - spotLights[i].outerCutOff) / epsilon, 0.0, 1.0);\n"
        "        float dist = length(spotLights[i].position - fs_in.FragPos);\n"
        "        float attenuation = 1.0 / (spotLights[i].constant + spotLights[i].linear * dist + spotLights[i].quadratic * dist * dist);\n"
        "        vec3 contrib = CalcLightContrib(spotLights[i].position - fs_in.FragPos, spotLights[i].diffuse, spotLights[i].specular,\n"
        "                                        normal, viewDir, albedo, metallic, roughness);\n"
        "        result += (spotLights[i].ambient * albedo + contrib * intensity) * attenuation * ao;\n"
        "    }\n"
        "\n"
        "    if (numDirLights == 0 && numPointLights == 0 && numSpotLights == 0) result = albedo * 0.15 * ao;\n"
        "\n"
        "    result = pow(max(result, vec3(0.0)), vec3(1.0 / 2.2));\n"
        "    FragColor = vec4(result, texColor.a * uColor.a);\n"
        "}\n";

    return LoadFromSource(vert.c_str(), frag.c_str());
}