#include "ShaderWater.h"

bool ShaderWater::CreateShader()
{
    std::string vert =
        "#version 460 core\n"
        "layout(location = 0) in vec3 aPos;\n"
        "out vec4 ScreenPos;\n"
        "out vec3 WorldPos;\n"
        "uniform mat4 model;\n"
        "uniform mat4 view;\n"
        "uniform mat4 projection;\n"
        "void main() {\n"
        "    vec4 wPos = model * vec4(aPos, 1.0);\n"
        "    WorldPos = wPos.xyz;\n"
        "    vec4 clipPos = projection * view * wPos;\n"
        "    ScreenPos = clipPos;\n"
        "    gl_Position = clipPos;\n"
        "}\n";

    std::string frag =
        "#version 460 core\n"
        "out vec4 FragColor;\n"
        "in vec4 ScreenPos;\n"
        "in vec3 WorldPos;\n"
        "uniform sampler2D uSceneDepthMap;\n"
        "uniform mat4 uInverseVP;\n"
        "uniform float uTime;\n"
        "uniform vec3 uWaterColor;\n"
        "uniform vec3 uFoamColor;\n"
        "uniform float uFoamThickness;\n"
        "uniform float uFoamOffset;\n"
        "\n"
        "vec3 GetWorldPosFromDepth(vec2 ndc, float rawDepth) {\n"
        "    vec4 clipSpace = vec4(ndc * 2.0 - 1.0, rawDepth * 2.0 - 1.0, 1.0);\n"
        "    vec4 worldSpace = uInverseVP * clipSpace;\n"
        "    return worldSpace.xyz / worldSpace.w;\n"
        "}\n"
        "\n"
        "void main() {\n"
        "    vec2 ndc = (ScreenPos.xy / ScreenPos.w) * 0.5 + 0.5;\n"
        "    float rawDepth = texture(uSceneDepthMap, ndc).r;\n"
        "\n"
        "    vec3 terrainWorldPos = GetWorldPosFromDepth(ndc, rawDepth);\n"
        "    float verticalDepth = WorldPos.y - terrainWorldPos.y;\n"
        "\n"
        "    // --- 1. MAREAS INDEPENDIENTES (Para que se pisen entre ellas) --- \n"
        "    \n"
        "    // A. Capa de la Orilla (Sube y baja suave)\n"
        "    float tideShore = sin(uTime * 1.0) * 0.05;\n"
        "    float wobbleShore = (sin(WorldPos.x * 3.0 + uTime * 1.2) + cos(WorldPos.z * 3.0 - uTime * 0.9)) * 0.01;\n"
        "    float depthShore = verticalDepth + wobbleShore - tideShore;\n"
        "\n"
        "    // B. Capa de Línea Fina (Más rápida, desfasada +1.5 para chocar con la orilla)\n"
        "    float tideLine = sin(uTime * 1.4 + 1.5) * 0.1;\n"
        "    float wobbleLine = (sin(WorldPos.x * 4.0 - uTime * 1.5) + cos(WorldPos.z * 4.0 + uTime * 1.2)) * 0.01;\n"
        "    float depthLine = verticalDepth + wobbleLine - tideLine;\n"
        "\n"
        "    // C. Capa de Banda Oscura (Lenta, desfasada +3.0 y con olas más anchas)\n"
        "    float tideDark = sin(uTime * 0.7 + 3.0) * 0.15;\n"
        "    float wobbleDark = (sin(WorldPos.x * 2.0 + uTime * 0.5) + cos(WorldPos.z * 2.0 - uTime * 0.5)) * 0.01;\n"
        "    float depthDark = verticalDepth + wobbleDark - tideDark;\n"
        "\n"
        "    // --- 2. CONFIGURACIÓN DE LAS 3 BANDAS --- \n"
        "    float shoreEnd = 0.25; \n"
        "    \n"
        "    float lineStart = 0.45;\n"
        "    float lineEnd = 0.50;\n"
        "\n"
        "    float darkStart = 0.70;\n"
        "    float darkEnd = 1.30;\n"
        "\n"
        "    // --- 3. DIBUJAR CADA LÍNEA CON SU PROPIA PROFUNDIDAD --- \n"
        "    // Ahora cada capa evalúa los metros con su propio 'reloj'\n"
        "    float isShore = 1.0 - step(shoreEnd, depthShore); \n"
        "    float isLine = step(lineStart, depthLine) - step(lineEnd, depthLine);\n"
        "    float isDark = step(darkStart, depthDark) - step(darkEnd, depthDark);\n"
        "\n"
        "    // --- 4. MEZCLADO DE COLORES --- \n"
        "    vec3 colorMar = vec3(0.051, 0.337, 1.0);       // #0D56FF \n"
        "    vec3 colorLineaLejos = vec3(0.051, 0.255, 1.0); // #0D41FF \n"
        "    vec3 colorLineaFina = vec3(0.176, 0.980, 0.980); // #2DFAFA \n"
        "    vec3 colorOrilla = vec3(0.580, 1.0, 1.0);       // #94FFFF \n"
        "\n"
        "    vec3 finalColor = colorMar;\n"
        "    \n"
        "    // ¡La magia del solapamiento ocurre aquí! \n"
        "    // Si la fina pisa a la oscura, se dibuja la fina. Si la orilla las pisa a todas, gana la orilla.\n"
        "    finalColor = mix(finalColor, colorLineaLejos, isDark);\n"
        "    finalColor = mix(finalColor, colorLineaFina, isLine);\n"
        "    finalColor = mix(finalColor, colorOrilla, isShore);\n"
        "\n"
        "    FragColor = vec4(finalColor, 1.0);\n"
        "}\n";

    return LoadFromSource(vert.c_str(), frag.c_str());
}