#include "ShaderWater.h"

bool ShaderWater::CreateShader()
{
    std::string vert =
        "#version 460 core\n"
        "layout(location = 0) in vec3 aPos;\n"
        "out vec4 ScreenPos;\n"
        "uniform mat4 model;\n"
        "uniform mat4 view;\n"
        "uniform mat4 projection;\n"
        "void main() {\n"
        "    vec4 worldPos = model * vec4(aPos, 1.0);\n"
        "    vec4 clipPos = projection * view * worldPos;\n"
        "    ScreenPos = clipPos;\n"
        "    gl_Position = clipPos;\n"
        "}\n";

    std::string frag =
        "#version 460 core\n"
        "out vec4 FragColor;\n"
        "in vec4 ScreenPos;\n"
        "uniform sampler2D uSceneDepthMap;\n"
        "uniform vec3 uWaterColor;\n"
        "uniform vec3 uFoamColor;\n"
        "uniform float uFoamThickness;\n" // Metros
        "uniform float uFoamOffset;\n"    // Metros
        "uniform float uNearPlane;\n"
        "uniform float uFarPlane;\n"
        "\n"
        "float LinearizeDepth(float depth) {\n"
        "    float z = depth * 2.0 - 1.0;\n"
        "    return (2.0 * uNearPlane * uFarPlane) / (uFarPlane + uNearPlane - z * (uFarPlane - uNearPlane));\n"
        "}\n"
        "\n"
        "void main() {\n"
        "    vec2 ndc = (ScreenPos.xy / ScreenPos.w) * 0.5 + 0.5;\n"
        "    float waterDepth = LinearizeDepth(gl_FragCoord.z);\n"
        "\n"
        "    // Averiguamos el Aspect Ratio para que el anillo no se vea ovalado\n"
        "    vec2 screenSize = textureSize(uSceneDepthMap, 0);\n"
        "    float aspect = screenSize.x / screenSize.y;\n"
        "\n"
        "    // CONVERSIÓN MÁGICA: Metros 3D -> Coordenadas UV adaptadas a la distancia de la cámara\n"
        "    // ScreenPos.w nos dice a qué distancia exacta está este píxel de tu ojo\n"
        "    float distScale = max(ScreenPos.w, 0.001);\n"
        "    vec2 radiusOffset = vec2((uFoamOffset / distScale) / aspect, uFoamOffset / distScale);\n"
        "    vec2 radiusTotal  = vec2(((uFoamOffset + uFoamThickness) / distScale) / aspect, (uFoamOffset + uFoamThickness) / distScale);\n"
        "\n"
        "    vec2 dirs[8] = vec2[](\n"
        "        vec2(1.0, 0.0), vec2(0.0, 1.0), vec2(-1.0, 0.0), vec2(0.0, -1.0),\n"
        "        vec2(0.707, 0.707), vec2(-0.707, 0.707), vec2(-0.707, -0.707), vec2(0.707, -0.707)\n"
        "    );\n"
        "\n"
        "    float isInsideOffset = 0.0;\n"
        "    float isInsideFoam = 0.0;\n"
        "    float tolerance = 0.05;\n"
        "\n"
        "    // 1. Mirar si hay tierra en el radio del hueco\n"
        "    for(int i = 0; i < 8; i++) {\n"
        "        vec2 sampleUV = ndc + dirs[i] * radiusOffset;\n"
        "        float sDepth = LinearizeDepth(texture(uSceneDepthMap, sampleUV).r);\n"
        "        if(sDepth <= waterDepth + tolerance) isInsideOffset = 1.0;\n"
        "    }\n"
        "\n"
        "    // 2. Mirar si hay tierra en el radio total (Hueco + Línea)\n"
        "    for(int i = 0; i < 8; i++) {\n"
        "        vec2 sampleUV = ndc + dirs[i] * radiusTotal;\n"
        "        float sDepth = LinearizeDepth(texture(uSceneDepthMap, sampleUV).r);\n"
        "        if(sDepth <= waterDepth + tolerance) isInsideFoam = 1.0;\n"
        "    }\n"
        "\n"
        "    float isFoam = clamp(isInsideFoam - isInsideOffset, 0.0, 1.0);\n"
        "\n"
        "    vec3 finalColor = mix(uWaterColor, uFoamColor, isFoam);\n"
        "    FragColor = vec4(finalColor, 1.0);\n"
        "}\n";

    return LoadFromSource(vert.c_str(), frag.c_str());
}