#include "ShaderStandard.h"

bool ShaderStandard::CreateShader()
{
    std::string vert = std::string(shaderHeader) + skinningDeclarations + skinningFunction +
        "layout(location = 0) in vec3 aPos;\n"
        "layout(location = 1) in vec3 aNormal;\n"
        "layout(location = 2) in vec2 aTexCoord;\n"
        "layout(location = 3) in ivec4 boneIDs;\n"
        "layout(location = 4) in vec4 weights;\n"
        "layout(location = 5) in vec3 aTangent;\n"
        "\n"
        "out VS_OUT {\n"
        "    vec3 FragPos;\n"
        "    vec2 TexCoord;\n"
        "    vec3 Normal;\n"
        "    mat3 TBN;\n"
        "    vec4 FragPosLightSpace;\n"  //
        "} vs_out;\n"
        "\n"
        "uniform mat4 lightSpaceMatrix;\n"  // 
        "\n"
        "void main() {\n"
        "    mat4 skinMat = GetSkinMatrix(boneIDs, weights);\n"
        "    vec4 worldPos = model * skinMat * vec4(aPos, 1.0);\n"
        "    \n"
        "    vs_out.FragPos = worldPos.xyz;\n"
        "    vs_out.TexCoord = aTexCoord;\n"
        "    vs_out.FragPosLightSpace = lightSpaceMatrix * worldPos;\n"  // 
        "    \n"
        "    mat3 normalMatrix = transpose(inverse(mat3(model * skinMat)));\n"
        "    vec3 N = normalize(normalMatrix * aNormal);\n"
        "    vec3 T = normalize(normalMatrix * aTangent);\n"
        "    T = normalize(T - dot(T, N) * N);\n"
        "    vec3 B = cross(T, N);\n"
        "    \n"
        "    vs_out.Normal = N;\n"
        "    vs_out.TBN = mat3(T, B, N);\n"
        "    \n"
        "    gl_Position = projection * view * worldPos;\n"
        "}\n";

    std::string frag =
        "#version 460 core\n"
        "out vec4 FragColor;\n"
        "\n"
        "in VS_OUT {\n"
        "    vec3 FragPos;\n"
        "    vec2 TexCoord;\n"
        "    vec3 Normal;\n"
        "    mat3 TBN;\n"
        "    vec4 FragPosLightSpace;\n"  //
        "} fs_in;\n"
        "\n"
        "uniform sampler2D uAlbedoMap;\n"
        "uniform sampler2D uNormalMap;\n"
        "uniform sampler2D uMetallicMap;\n"
        "uniform sampler2D uOcclusionMap;\n"
        "uniform sampler2D uHeightMap;\n"
        "uniform sampler2D uShadowMap;\n"  //
        "\n"
        "uniform vec4  uColor;\n"
        "uniform float uHeightScale;\n"
        "uniform float uMetallic;\n"
        "uniform float uRoughness;\n"
        "uniform vec2  uTiling;\n"
        "uniform vec2  uOffset;\n"
        "uniform vec3  viewPos;\n"
        "\n"
        "uniform bool uUseNormalMap;\n"
        "uniform bool uUseMetallicMap;\n"
        "uniform bool uUseOcclusionMap;\n"
        "uniform bool uUseHeightMap;\n"
        "\n"
        "struct DirLightGLSL {\n"
        "    vec3 direction; float _p0;\n"
        "    vec3 ambient;   float _p1;\n"
        "    vec3 diffuse;   float _p2;\n"
        "    vec3 specular;  float _p3;\n"
        "};\n"
        "\n"
        "struct PointLightGLSL {\n"
        "    vec3 position;  float _p0;\n"
        "    vec3 ambient;   float _p1;\n"
        "    vec3 diffuse;   float _p2;\n"
        "    vec3 specular;  float _p3;\n"
        "    float constant;\n"
        "    float linear;\n"
        "    float quadratic;\n"
        "    float _p4;\n"
        "};\n"
        "\n"
        "struct SpotLightGLSL {\n"
        "    vec3 position;    float _p0;\n"
        "    vec3 direction;   float _p1;\n"
        "    vec3 ambient;     float _p2;\n"
        "    vec3 diffuse;     float _p3;\n"
        "    vec3 specular;    float _p4;\n"
        "    float cutOff;\n"
        "    float outerCutOff;\n"
        "    float constant;\n"
        "    float linear;\n"
        "    float quadratic;\n"
        "    float _p5; float _p6; float _p7;\n"
        "};\n"
        "\n"
        "layout(std430, binding = 2) readonly buffer DirLightBuffer   { DirLightGLSL   dirLights[];   };\n"
        "layout(std430, binding = 3) readonly buffer PointLightBuffer { PointLightGLSL pointLights[]; };\n"
        "layout(std430, binding = 4) readonly buffer SpotLightBuffer  { SpotLightGLSL  spotLights[];  };\n"
        "\n"
        "uniform int numDirLights;\n"
        "uniform int numPointLights;\n"
        "uniform int numSpotLights;\n"
        "\n"

        // Shadow calculation con PCF
        "float ShadowCalculation(vec4 fragPosLightSpace, vec3 normal, vec3 lightDir) {\n"
        "    vec3 projCoords = fragPosLightSpace.xyz / fragPosLightSpace.w;\n"
        "    projCoords = projCoords * 0.5 + 0.5;\n"
        "\n"
        "    if (projCoords.z > 1.0) return 0.0;\n"
        "\n"
        "    float bias = max(0.005 * (1.0 - dot(normal, lightDir)), 0.0005);\n"
        "\n"
        "    float shadow = 0.0;\n"
        "    vec2 texelSize = 1.0 / textureSize(uShadowMap, 0);\n"
        "    for (int x = -1; x <= 1; ++x) {\n"
        "        for (int y = -1; y <= 1; ++y) {\n"
        "            float pcfDepth = texture(uShadowMap, projCoords.xy + vec2(x, y) * texelSize).r;\n"
        "            shadow += (projCoords.z - bias) > pcfDepth ? 1.0 : 0.0;\n"
        "        }\n"
        "    }\n"
        "    shadow /= 9.0;\n"
        "    return shadow;\n"
        "}\n"
        "\n"

        "vec2 ParallaxMapping(vec2 texCoords, vec3 viewDir) {\n"
        "    float height = texture(uHeightMap, texCoords).r;\n"
        "    return texCoords - viewDir.xy * (height * uHeightScale);\n"
        "}\n"
        "\n"

        "vec3 CalcLightContrib(vec3 lightDir, vec3 diffuseColor, vec3 specularColor,\n"
        "                      vec3 norm, vec3 viewDir,\n"
        "                      vec3 albedo, float metallic, float roughness) {\n"
        "    vec3 L = normalize(lightDir);\n"
        "    float diff = max(dot(norm, L), 0.0);\n"
        "\n"
        "    vec3 H = normalize(L + viewDir);\n"
        "    float shininess = (1.0 - clamp(roughness, 0.05, 1.0)) * 128.0 + 1.0;\n"
        "    float spec = pow(max(dot(norm, H), 0.0), shininess);\n"
        "\n"
        "    vec3 F0 = mix(vec3(0.04), albedo, metallic);\n"
        "\n"
        "    vec3 diffContrib = diffuseColor  * diff * albedo * (1.0 - metallic);\n"
        "    vec3 specContrib = specularColor * spec * F0;\n"
        "\n"
        "    return diffContrib + specContrib;\n"
        "}\n"
        "\n"

        "void main() {\n"
        "    vec2 uv = fs_in.TexCoord * uTiling + uOffset;\n"
        "\n"
        "    vec3 viewDir = normalize(viewPos - fs_in.FragPos);\n"
        "\n"
        "    if(uUseHeightMap && uHeightScale > 0.0) {\n"
        "        vec3 viewDirTangent = normalize(transpose(fs_in.TBN) * viewDir);\n"
        "        uv = ParallaxMapping(uv, viewDirTangent);\n"
        "    }\n"
        "\n"
        "    vec3 normal;\n"
        "    if(uUseNormalMap) {\n"
        "        normal = texture(uNormalMap, uv).rgb;\n"
        "        normal = normalize(normal * 2.0 - 1.0);\n"
        "        normal = normalize(fs_in.TBN * normal);\n"
        "    } else {\n"
        "        normal = normalize(fs_in.Normal);\n"
        "    }\n"
        "\n"
        "    vec4 texColor = texture(uAlbedoMap, uv);\n"
        "    vec3 albedo = pow(texColor.rgb, vec3(2.2)) * uColor.rgb;\n"
        "\n"
        "    float metallic = uUseMetallicMap\n"
        "        ? texture(uMetallicMap, uv).r * uMetallic\n"
        "        : uMetallic;\n"
        "\n"
        "    float ao = uUseOcclusionMap\n"
        "        ? texture(uOcclusionMap, uv).r\n"
        "        : 1.0;\n"
        "\n"
        "    float roughness = clamp(uRoughness, 0.05, 1.0);\n"
        "\n"
        "    vec3 result = vec3(0.0);\n"
        "\n"
        // Luces direccionales con sombra
        "    for (int i = 0; i < numDirLights; ++i) {\n"
        "        vec3 lightDir = normalize(-dirLights[i].direction);\n"
        "        float shadow = (i == 0)\n"
        "            ? ShadowCalculation(fs_in.FragPosLightSpace, normal, lightDir)\n"
        "            : 0.0;\n"
        "\n"
        "        vec3 ambient = dirLights[i].ambient * albedo * ao;\n"
        "        vec3 contrib = CalcLightContrib(\n"
        "            lightDir,\n"
        "            dirLights[i].diffuse,\n"
        "            dirLights[i].specular,\n"
        "            normal, viewDir, albedo, metallic, roughness\n"
        "        );\n"
        "        result += ambient + contrib * (1.0 - shadow) * ao;\n"
        "    }\n"
        "\n"
        // Punto y spot SIN sombra
        "    for (int i = 0; i < numPointLights; ++i) {\n"
        "        float dist        = length(pointLights[i].position - fs_in.FragPos);\n"
        "        float attenuation = 1.0 / (pointLights[i].constant\n"
        "                                 + pointLights[i].linear    * dist\n"
        "                                 + pointLights[i].quadratic * dist * dist);\n"
        "\n"
        "        vec3 ambient = pointLights[i].ambient * albedo * ao;\n"
        "        vec3 contrib = CalcLightContrib(\n"
        "            pointLights[i].position - fs_in.FragPos,\n"
        "            pointLights[i].diffuse,\n"
        "            pointLights[i].specular,\n"
        "            normal, viewDir, albedo, metallic, roughness\n"
        "        );\n"
        "        result += (ambient + contrib) * attenuation * ao;\n"
        "    }\n"
        "\n"
        "    for (int i = 0; i < numSpotLights; ++i) {\n"
        "        vec3  L         = normalize(spotLights[i].position - fs_in.FragPos);\n"
        "        float theta     = dot(L, normalize(-spotLights[i].direction));\n"
        "        float epsilon   = spotLights[i].cutOff - spotLights[i].outerCutOff;\n"
        "        float intensity = clamp((theta - spotLights[i].outerCutOff) / epsilon, 0.0, 1.0);\n"
        "\n"
        "        float dist        = length(spotLights[i].position - fs_in.FragPos);\n"
        "        float attenuation = 1.0 / (spotLights[i].constant\n"
        "                                 + spotLights[i].linear    * dist\n"
        "                                 + spotLights[i].quadratic * dist * dist);\n"
        "\n"
        "        vec3 ambient = spotLights[i].ambient * albedo * ao;\n"
        "        vec3 contrib = CalcLightContrib(\n"
        "            spotLights[i].position - fs_in.FragPos,\n"
        "            spotLights[i].diffuse,\n"
        "            spotLights[i].specular,\n"
        "            normal, viewDir, albedo, metallic, roughness\n"
        "        );\n"
        "        result += (ambient + contrib * intensity) * attenuation * ao;\n"
        "    }\n"
        "\n"
        "    if (numDirLights == 0 && numPointLights == 0 && numSpotLights == 0) {\n"
        "        result = albedo * 0.15 * ao;\n"
        "    }\n"
        "\n"
        "    result = pow(max(result, vec3(0.0)), vec3(1.0 / 2.2));\n"
        "\n"
        "    FragColor = vec4(result, texColor.a * uColor.a);\n"
        "}\n";

    return LoadFromSource(vert.c_str(), frag.c_str());
}